openapi: 3.1.0
servers:
  - url: http://localhost
info:
  title: Prompting API
  summary: The API for communication between snapd and prompt UI clients
  version: 0.0.1
  description: >
    The API for communication between snapd and prompt UI clients.
components:
  schemas:
    follow:
      description: >
        Whether or not to open a long-lived connection.
      type: boolean
    request-id:
      description: >
        The unique ID of a prompt request.
      type: string
    rule-id:
      description: >
        The unique ID of an access rule.
      type: string
    timestamp:
      description: >
        The timestamp at which an access rule was created or last modified.
      type: string
      format: date-time
    snap:
      description: >
        The name of the snap which corresponds to the prompt request or access
        rule.
      type: string
    app:
      description: >
        The name of the app which corresponds to the prompt request or access
        rule.
      type: string
    path:
      description: >
        The path of the object of the prompt request or access rule.
      type: string
    permission:
      description: >
        The operation for which a prompt request or access rule applies.
      type: string
      enum:
        - execute                # AA_MAY_EXEC, process may execute another program
        - write                  # AA_MAY_WRITE, process may write to a file or socket
        - read                   # AA_MAY_READ, process may read from a file or socket, or enumerate directory contents
        - append                 # AA_MAY_APPEND, process may open a file in append mode
        - create                 # AA_MAY_CREATE, process may create a new file
        - delete                 # AA_MAY_DELETE, process may delete a file, directory, symbolic link, or socket
        - open                   # AA_MAY_OPEN, process may open a file or directory, the additional presence of write or read grants specific type of access
        - rename                 # AA_MAY_RENAME, process may rename a file
        - set-attribute          # AA_MAY_SETATTR, not checked by the kernel
        - get-attribute          # AA_MAY_GETATTR, not checked by the kernel
        - set-credential         # AA_MAY_SETCRED, not used in the kernel
        - get-credential         # AA_MAY_GETCRED, not used in the kernel
        - change-mode            # AA_MAY_CHMOD, process may change UNIX file permissions
        - change-owner           # AA_MAY_CHOWN, process may change file ownership
        - change-group           # AA_MAY_CHGRP, process may change the group ownership of a file
        - lock                   # AA_MAY_LOCK, process may perform fcntl locking operations on file
        - execute-map            # AA_EXEC_MMAP, process may execute code from a page memory-mapped from a file
        - link                   # AA_MAY_LINK, process may create hard link
        - change-profile-on-exec # AA_MAY_ONEXEC, process may change the apparmor profile on the next exec call
        - change-profile         # AA_MAY_CHANGE_PROFILE, process may change the apparmor profile on demand
    allow:
      description: >
        Whether to allow or deny access.
      type: boolean
    lifespan:
      description: >
        The lifespan for which the access rule should be valid.
      type: string
      enum:
        - single
        - session
        - always
        - timeframe # TODO: how to store the timeframe?
    permissions:
      description: >
        The list of permissions for which a prompt request or access rule
        applies.
      type: array
      items:
        $ref: "#/components/schemas/permission"
    path-scope:
      description: >
        Apply the same rule on either the path itself, all other files in the
        directory of the requested path, or all other files in the path's
        directory and all subdirectories.

        The subdirectories value is a superset of the the directory value.

        If the requested path is a file, then directory access refers to
        accessing files in the parent directory of the path.

        If the requested path is a directory, then directory access refers to
        accessing files in that directory.
      type: string
      enum:
        - file
        - directory
        - subdirectories
    request:
      description: >
        An outstanding prompt request for the given snap and app to access
        the given path with the given permissions.
      type: object
      required:
        - request-id
        - snap
        - app
        - path
        - permissions
      properties:
        request-id:
          $ref: "#/components/schemas/request-id"
        snap:
          $ref: "#/components/schemas/snap"
        app:
          $ref: "#/components/schemas/app"
        path:
          $ref: "#/components/schemas/path"
        permissions:
          $ref: "#/components/schemas/permissions"
    reply:
      description: >
        A reply to a prompt request.
      type: object
      required:
        - allow
        - lifespan
      properties:
        allow:
          $ref: "#/components/schemas/allow"
        lifespan:
          $ref: "#/components/schemas/lifespan"
        permissions:
          $ref: "#/components/schemas/permissions"
        path-scope:
          $ref: "#/components/schemas/path-scope"
      # store-parent:
      #   description: >
      #     Store the parent of the requested path in the database,
      #     rather than the path itself.
      #   type: boolean
    rule-metadata:
      description: >
        The metadata for an access rule, including the unique rule ID and the
        timestamp at which that rule was created or modified.
      type: object
      required:
        - rule-id
        - timestamp
      properties:
        rule-id:
          $ref: "#/components/schemas/rule-id"
        timestamp:
          $ref: "#/components/schemas/timestamp"
    rule-contents:
      description: >
        The body of an access rule.
      type: object
      required:
        - snap
        - app
        - path
        - allow
        - lifespan
        - permissions
        - path-scope
      properties:
        snap:
          $ref: "#/components/schemas/snap"
        app:
          $ref: "#/components/schemas/app"
        path:
          $ref: "#/components/schemas/path"
        allow:
          $ref: "#/components/schemas/allow"
        lifespan:
          $ref: "#/components/schemas/lifespan"
        permissions:
          $ref: "#/components/schemas/permissions"
        path-scope:
          $ref: "#/components/schemas/path-scope"
    rule:
      description: >
        A saved access rule with a corresponding ID and timestamp.
      allOf:
        - $ref: "#/components/schemas/rule-metadata"
        - $ref: "#/components/schemas/rule-contents"
    changed-rules:
      description: >
        The access rules which have been created, modified, or deleted as
        the result of a change.
      type: object
      properties:
        new:
          description: >
            The access rules which have been created.
          type: array
          items:
            $ref: "#/components/schemas/rule"
        modified:
          description: >
            The access rules which have been modified.
          type: array
          items:
            $ref: "#/components/schemas/rule"
        deleted:
          description: >
            The access rules which have been deleted.
          type: array
          items:
            $ref: "#/components/schemas/rule"
  parameters:
    request-id-param:
      description: >
        The ID of the prompt request.
      name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/request-id"
    rule-id-param:
      description: >
        The ID of the access rule.
      name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/rule-id"
tags:
  - name: requests
    description: Methods related to outstanding prompt requests.
  - name: rules
    description: Methods related to stored access rules.
paths:
  /v2/prompting/requests:
    GET:
      operationId: getRequests
      summary: Retrieve all prompt requests
      description: >
        Retrieve all outstanding prompt requests.
      tags:
        - requests
      parameters:
        - name: follow
          in: query
          description: >
            Open a long-lived connection using "json-seq" to be notified of
            any future prompt requests.
          required: false
          schema:
            $ref: "#/components/schemas/follow"
      responses:
        "200":
          description: >
            Successfully retrieved all outstanding prompt requests.
          content:
            application/json:
              schema:
                description: >
                  The prompt requests which are currently pending.
                type: array
                items:
                  $ref: "#/components/schemas/request"
        "404":
          description: >
            Failed to retrieve prompt requests.
  /v2/prompting/requests/{id}:
    GET:
      operationId: getRequestWithId
      summary: Retrieve the information for a particular prompt request
      description: >
        Retrieve the prompt request information corresponding to the given ID.
      tags:
        - requests
      parameters:
        - $ref: "#/components/parameters/request-id-param"
      responses:
        "200":
          description: >
            Successfully retrieved the request information for the prompt
            request with the given ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/request"
        "404":
          description: >
            No prompt request found with the given ID.
    POST:
      operationId: replyToRequestWithId
      summary: Reply to the given prompt request
      description: >
        Respond to the given prompt request, providing information collected
        by prompting the user for a decision about access to the object of
        the request.
      tags:
        - requests
      parameters:
        - $ref: "#/components/parameters/request-id-param"
      requestBody:
        description: >
          The contents of the reply to the prompt request.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reply"
      responses:
        "200":
          description: >
            Successfully received the reply for the prompt request with the
            given ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/changed-rules"
        "404":
          description: >
            No request found with the given ID, ignoring reply.
  /v2/access-control/rules:
    GET:
      operationId: getRules
      summary: Get existing access rules
      description: >
        Retrieve existing access rules from the rule database.

        If the snap parameter is given, only retrieve rules for that snap.

        If the app parameter is given along with the snap parameter, only
        retrieve rules for that app within the given snap.

        The follow and the app parameters are both ignored if the snap
        parameter is not given.
      tags:
        - rules
      parameters:
        - name: snap
          in: query
          description: >
            The snap for which to retrieve access rules.
          required: false
          schema:
            $ref: "#/components/schemas/snap"
        - name: app
          in: query
          description: >
            The app within the given snap for which to retrieve access rules.

            Returns an error if the `app` parameter is given without the `snap`
            parameter also being given.
          required: false
          schema:
            $ref: "#/components/schemas/app"
        - name: follow
          in: query
          description: >
            Open a long-lived connection using "json-seq" to be notified of
            future changes to stored rules.

            Returns an error if the `follow` parameter is given without `snap`
            parameter also being given.
          required: false
          schema:
            $ref: "#/components/schemas/follow"
      responses:
        "200":
          description: >
            Successfully retrieved existing access rules from the rule
            database.
          content:
            application/json:
              schema:
                description: >
                  The existing access rules.
                type: array
                items:
                  $ref: "#/components/schemas/rule"
        "400":
          description: >
            The `snap` parameter is required when using the `app` or `follow`
            parameters.
        "404":
          description: >
            Failed to retrieve existing access rules from the rule database.
    POST:
      operationId: addRule
      summary: Create a new access rule
      description: >
        Directly create a new access rule without having previously been
        prompted with a prompt request.
      tags:
        - rules
      requestBody:
        description: >
          The contents of the access rule to be added.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/rule-contents"
      responses:
        "200":
          description: >
            Successfully added the given access rule.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/changed-rules"
        "404":
          description: >
            Failed to create the given access rule.
    DELETE:
      operationId: deleteRules
      summary: Delete existing access rules
      description: >
        Delete previously-stored access rules for the given snap from the rule
        database.

        If the `app` parameter is given, only delete rules for that app within
        the given snap.
      tags:
        - rules
      parameters:
        - name: snap
          in: query
          description: >
            The snap for which to delete access rules.
          required: true
          schema:
            $ref: "#/components/schemas/snap"
        - name: app
          in: query
          description: >
            The app within the given snap for which to delete access rules.
          required: false
          schema:
            $ref: "#/components/schemas/app"
        - name: confirm-delete
          in: query
          description: >
            Confirm that all the rules for the given snap (optionally, app)
            should be deleted.
          required: true
          schema:
            description: >
              Whether the rules should be deleted.
            type: boolean
      responses:
        "200":
          description: >
            Successfully deleted access rules.
            All deleted rules can be found in the response content.
          content:
            application/json:
              schema:
                description: >
                  The access rules which were deleted.
                type: array
                items:
                  $ref: "#/components/schemas/rule"
        "404":
          description: >
            Failed to delete access rules from the rule database.
  /v2/access-control/rules/{id}:
    GET:
      operationId: getRuleWithId
      summary: Get a particular access rule
      description: >
        Get the access rule corresponding to the given rule ID.
      tags:
        - rules
      parameters:
        - $ref: "#/components/parameters/rule-id-param"
      responses:
        "200":
          description: >
            Successfully retrieved the access rule with the given ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rule"
        "404":
          description: >
            No access rule found with the given ID.
    POST:
      operationId: modifyRuleWithId
      summary: Modify an existing access rule
      description: >
        Modify the access rule corresponding to the given request ID.
      tags:
        - rules
      parameters:
        - $ref: "#/components/parameters/rule-id-param"
      requestBody:
        description: >
          The updated contents of the reply for the given access rule.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reply"
      responses:
        "200":
          description: >
            Successfully modified the access rule with the given ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/changed-rules"
        "404":
          description: >
            No access rule found with the given ID.
            Ignored the given reply information.
    DELETE:
      operationId: deleteRuleWithId
      summary: Delete an access rule.
      description: >
        Delete the access rule with the given ID.
      tags:
        - rules
      parameters:
        - $ref: "#/components/parameters/rule-id-param"
      responses:
        "200":
          description: >
            Successfully deleted the access rule with the given ID.
            It can be found in the response content.
          content:
            applications/json:
              schema:
                $ref: "#/components/schemas/rule"
        "404":
          description: >
            No access rule found with the given ID.
            Failed to delete rule.

