name: validate-openapi-spec
run-name: New push or PR from ${{ github.actor }}
on:
  push:
    paths:
      - openapi.yaml
jobs:
  validate-openapi-yaml:
    runs-on: self-hosted
    steps:
      - name: Checkout API
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install openapi-spec-validator
        run: pip install openapi-spec-validator
      - name: Install vacuum linter to /tmp
        run: curl -fsSL https://quobix.com/scripts/install_vacuum.sh | INSTALL_DIR="/tmp" sh
      - name: Create sanitized API with lowercase HTTP verbs
        run: ./sanitize_openapi.sh
      - name: Validate API
        run: openapi-spec-validator openapi_sanitized.yaml
      - name: Lint API
        run: /tmp/vacuum lint openapi_sanitized.yaml
