name: validate-openapi-spec
run-name: New push or PR from ${{ github.actor }}
on:
  push:
    paths:
      - openapi.yaml
jobs:
  validate-openapi-yaml:
    runs-on: self-hosted
    steps:
      - name: Checkout API
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install openapi-spec-validator
        run: pip install openapi-spec-validator
      - name: Install vacuum linter to /tmp
        run: curl -fsSL https://quobix.com/scripts/install_vacuum.sh | INSTALL_DIR="/tmp" sh
      - name: Create cleaned API with lowercase HTTP verbs
        run: |
          cat openapi.yaml \
          | sed 's/GET/get/g' \
          | sed 's/POST/post/g' \
          | sed 's/PUT/put/g' \
          | sed 's/DELETE/delete/g' \
          | sed 's/PATCH/patch/g' > openapi_cleaned.yaml
      - name: Validate API
        run: openapi-spec-validator openapi_cleaned.yaml
      - name: Lint API
        run: /tmp/vacuum lint openapi_cleaned.yaml
